# Form implementation generated from reading ui file 'Dang_nhap.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
#pyuic6 -x A_Table.ui -o A_Table.py

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(244, 196)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Name_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Name_text.setGeometry(QtCore.QRect(60, 40, 141, 20))
        self.Name_text.setInputMask("")
        self.Name_text.setText("")
        self.Name_text.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.Name_text.setObjectName("Name_text")
        self.pass_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pass_text.setGeometry(QtCore.QRect(60, 70, 141, 20))
        self.pass_text.setInputMask("")
        self.pass_text.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pass_text.setObjectName("pass_text")
        self.QMK_text = QtWidgets.QPushButton(parent=self.centralwidget)
        self.QMK_text.setGeometry(QtCore.QRect(60, 100, 61, 21))
        self.QMK_text.setObjectName("QMK_text")
        self.Dang_nhap_bt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Dang_nhap_bt.setGeometry(QtCore.QRect(130, 100, 71, 21))
        self.Dang_nhap_bt.setObjectName("Dang_nhap_bt")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 31, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 244, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Name_text.setPlaceholderText(_translate("MainWindow", "Name"))
        self.pass_text.setPlaceholderText(_translate("MainWindow", "PassWord"))
        self.QMK_text.setText(_translate("MainWindow", "Quyên MK"))
        self.Dang_nhap_bt.setText(_translate("MainWindow", "Đăng nhập"))
        self.label.setText(_translate("MainWindow", "Đăng Nhập "))
        self.label_2.setText(_translate("MainWindow", "name"))
        self.label_3.setText(_translate("MainWindow", "pass"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
